import { useState, useEffect, useCallback, useMemo } from 'react';
import { Moon, Sun, Mic, MicOff, Loader2, X, ExternalLink, MessageSquareText } from 'lucide-react';
import { Toaster, toast } from 'react-hot-toast';
import { updateSession } from './lib/firebase';
import { analyzeWithGemini } from './lib/gemini';
import { formatAnalysisWithLinks, extractUrls, extractKeywords } from './lib/formatters';
import { useSpeechRecognition } from './hooks/useSpeechRecognition';
import { TranscriptionTimeline } from './components/TranscriptionTimeline';
import { MobileLayout } from './components/MobileLayout';

interface Transcription {
  id: string;
  text: string;
  timestamp: string;
  isAnalyzed: boolean;
  keywords?: string[];
  selectedKeywords?: string[];
  analysis?: string;
  sources?: string[];
  summary?: string;
}

function App() {
  const [darkMode, setDarkMode] = useState(() => {
    const savedMode = localStorage.getItem('darkMode');
    return savedMode ? JSON.parse(savedMode) : false;
  });

  const [transcriptions, setTranscriptions] = useState<Transcription[]>([]);
  const [liveTranscription, setLiveTranscription] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [error, setError] = useState('');
  const [currentUrl, setCurrentUrl] = useState('');
  const [allKeywords, setAllKeywords] = useState<string[]>([]);
  const [conversationSummary, setConversationSummary] = useState('');
  const [selectedTranscriptionId, setSelectedTranscriptionId] = useState<string | null>(null);
  const [isInSession, _setIsInSession] = useState(false);
  const [sessionCode, _setSessionCode] = useState('');
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [_currentTranscriptionText, setCurrentTranscriptionText] = useState<string | null>(null);

  useEffect(() => {
    if (transcriptions.length > 0) {
      const latestTranscription = transcriptions[0];
      setSelectedTranscriptionId(latestTranscription.id);
      setCurrentTranscriptionText(latestTranscription.text);
      if (latestTranscription.sources && latestTranscription.sources.length > 0) {
        setCurrentUrl(latestTranscription.sources[0]);
      }
    }
  }, [transcriptions]);

  const speechRecognitionConfig = useMemo(() => ({
    onBatchComplete: async (text: string) => {
      const transcription: Transcription = {
        id: Date.now().toString(),
        text,
        timestamp: new Date().toISOString(),
        isAnalyzed: false,
        keywords: [],
        selectedKeywords: [],
        analysis: '',
        sources: [],
        summary: ''
      };
      setTranscriptions(prev => [transcription, ...prev]);
      await processTranscription(transcription);
    },
    onLiveTranscription: setLiveTranscription,
    onError: (error: string) => {
      toast.error(error);
    }
  }), []);

  const { isRecording, startRecording, stopRecording } = useSpeechRecognition(speechRecognitionConfig);

  useEffect(() => {
    localStorage.setItem('darkMode', JSON.stringify(darkMode));
    if (darkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [darkMode]);

  const processTranscription = useCallback(async (transcriptionToProcess: Transcription) => {
    try {
      setIsProcessing(true);
      setError('');
      setCurrentTranscriptionText(transcriptionToProcess.text);

      const { analysis: keywordsResponse } = await analyzeWithGemini(transcriptionToProcess.text, [], true);
      if (!keywordsResponse) {
        throw new Error('Failed to extract keywords');
      }
      const newKeywords = extractKeywords(keywordsResponse);
      if (!newKeywords || !Array.isArray(newKeywords)) {
        throw new Error('Invalid keywords format received');
      }

      setIsSummarizing(true);
      const keywordsForAnalysis = transcriptionToProcess.selectedKeywords || [];
      const { analysis, summary } = await analyzeWithGemini(
        transcriptionToProcess.text,
        keywordsForAnalysis,
        false,
        transcriptions.map(t => ({ text: t.text, timestamp: t.timestamp }))
      );

      if (!analysis) {
        throw new Error('Failed to generate analysis');
      }
      if (!summary) {
        console.warn("Conversation summary was not generated by Gemini API.");
      }

      const newUrls = extractUrls(analysis);

      setAllKeywords(prev => {
        const uniqueKeywords = [...new Set([...prev, ...newKeywords])];
        return uniqueKeywords.sort();
      });

      setTranscriptions(prev =>
        prev.map(t =>
          t.id === transcriptionToProcess.id ? {
            ...t,
            isAnalyzed: true,
            keywords: newKeywords,
            analysis: analysis,
            sources: newUrls,
            summary: summary
          } : t
        )
      );

      if (summary) {
        setConversationSummary(summary);
      }

      if (isInSession && sessionCode) {
        await updateSession(sessionCode, {
          transcriptions,
          analysis,
          urlList: newUrls,
          keywords: allKeywords,
          summary
        });
      }

    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'An unknown error occurred';
      console.error('Error processing transcription:', errorMessage);
      toast.error(`Failed to process transcription: ${errorMessage}`);
      setError(errorMessage);
    } finally {
      setIsProcessing(false);
      setCurrentTranscriptionText(null);
    }
  }, [transcriptions, isInSession, sessionCode, allKeywords]);

  const clearConversation = useCallback(() => {
    setTranscriptions([]);
    setCurrentUrl('');
    setAllKeywords([]);
    setConversationSummary('');
    setCurrentTranscriptionText(null);
    setSelectedTranscriptionId(null);
    toast.success('Conversation cleared');
  }, []);

  const toggleKeyword = useCallback((keyword: string, transcriptionId: string) => {
    setTranscriptions(prev =>
      prev.map(t => {
        if (t.id === transcriptionId) {
          const isSelected = t.selectedKeywords?.includes(keyword);
          const updatedKeywords = isSelected
            ? t.selectedKeywords?.filter(k => k !== keyword) || []
            : [...(t.selectedKeywords || []), keyword];

          if (t.isAnalyzed) {
            processTranscription({ ...t, selectedKeywords: updatedKeywords });
          }

          return { ...t, selectedKeywords: updatedKeywords };
        }
        return t;
      })
    );
  }, [processTranscription]);

  const handleTranscriptionSelect = useCallback((id: string) => {
    setSelectedTranscriptionId(id);
    const transcription = transcriptions.find(t => t.id === id);
    if (transcription) {
      setCurrentTranscriptionText(transcription.text);
      setCurrentUrl(transcription.sources && transcription.sources[0] || '');
    }
  }, [transcriptions]);

  const renderAnalysis = (analysisText: string | undefined) => {
    return (
      <div
        dangerouslySetInnerHTML={{
          __html: formatAnalysisWithLinks(analysisText || '')
        }}
      />
    );
  };

  const RecordingControls = () => (
    <div className="flex gap-2">
      <button
        onClick={startRecording}
        disabled={isRecording}
        className={`p-3 rounded-lg transition-colors ${isRecording
          ? 'bg-gray-300 cursor-not-allowed'
          : 'bg-blue-600 hover:bg-blue-700'
          }`}
        aria-label="Start Recording"
      >
        <Mic className={`w-5 h-5 ${isRecording ? 'text-gray-500' : 'text-white'}`} />
      </button>

      <button
        onClick={stopRecording}
        disabled={!isRecording}
        className={`p-3 rounded-lg transition-colors ${!isRecording
          ? 'bg-gray-300 cursor-not-allowed'
          : 'bg-red-600 hover:bg-red-700'
          }`}
        aria-label="Stop Recording"
      >
        <MicOff className={`w-5 h-5 ${!isRecording ? 'text-gray-500' : 'text-white'}`} />
      </button>

      <button
        onClick={clearConversation}
        className={`p-3 rounded-lg ${darkMode
          ? 'bg-gray-800 text-gray-200 hover:bg-gray-700'
          : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
          }`}
        aria-label="Clear Conversation"
      >
        <X className="w-5 h-5" />
      </button>
    </div>
  );

  const KeywordPanel = () => {
    const uniqueKeywordsFromAll = useMemo(() => {
      const keywords = transcriptions.reduce((acc: string[], t) => {
        return [...acc, ...(t.keywords || [])];
      }, []);
      return [...new Set(keywords)].sort();
    }, [transcriptions]);

    const lastTranscription = transcriptions[0];
    const selectedKeywordsForLast = lastTranscription?.selectedKeywords || [];

    return (
      <div className="p-4 h-full overflow-y-auto">
        <div className="flex flex-col gap-2">
          {uniqueKeywordsFromAll.map((keyword, index) => (
            <button
              key={index}
              onClick={() => lastTranscription && toggleKeyword(keyword, lastTranscription.id)}
              disabled={!lastTranscription}
              className={`px-3 py-2 rounded-lg text-sm transition-colors text-left ${selectedKeywordsForLast.includes(keyword)
                ? darkMode
                  ? 'bg-green-900 text-green-200'
                  : 'bg-green-100 text-green-700'
                : darkMode
                  ? 'bg-gray-700 text-gray-300 hover:bg-gray-600'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                } ${!lastTranscription ? 'opacity-50 cursor-not-allowed' : ''}`}
            >
              {keyword}
            </button>
          ))}
        </div>
      </div>
    );
  };

  const AnalysisPanel = () => {
    const selectedTranscription = transcriptions.find(t => t.id === selectedTranscriptionId);
    const analysisToRender = selectedTranscription?.analysis;

    return (
      <div className="p-6 h-full overflow-y-auto">
        {isProcessing ? (
          <div className="flex items-center justify-center py-8">
            <Loader2 className={`w-8 h-8 animate-spin ${darkMode ? 'text-blue-400' : 'text-blue-500'}`} />
          </div>
        ) : error ? (
          <div className={`${darkMode ? 'bg-red-900' : 'bg-red-50'} p-4 rounded-lg`}>
            <p className={`${darkMode ? 'text-red-300' : 'text-red-600'}`}>Error: {error}</p>
          </div>
        ) : analysisToRender ? (
          <div className={`prose ${darkMode ? 'prose-invert' : ''} max-w-none`}>
            {renderAnalysis(analysisToRender)}
          </div>
        ) : (
          <div className={`p-4 ${darkMode ? 'text-gray-400' : 'text-gray-600'} text-center`}>
            {transcriptions.length === 0 ? "Start recording to see analysis." : "Select a transcription to view its analysis."}
          </div>
        )}
      </div>
    );
  };

  const SourcesPanel = () => {
    const selectedTranscription = transcriptions.find(t => t.id === selectedTranscriptionId);
    const sourcesToRender = selectedTranscription?.sources || [];

    return (
      <div className="p-4 h-full overflow-y-auto">
        {sourcesToRender.length > 0 ? (
          <div className="space-y-4">
            <div className="flex gap-2 overflow-x-auto pb-2">
              {sourcesToRender.map((url, index) => (
                <button
                  key={index}
                  onClick={() => setCurrentUrl(url)}
                  className={`px-3 py-1 rounded-full text-sm whitespace-nowrap ${currentUrl === url
                    ? darkMode ? 'bg-blue-900 text-blue-200' : 'bg-blue-100 text-blue-700'
                    : darkMode ? 'bg-gray-700 text-gray-300 hover:bg-gray-600' : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                    }`}
                >
                  Source {index + 1}
                </button>
              ))}
            </div>
            {currentUrl && (
              <div className="h-[calc(100vh-32rem)] bg-white rounded-lg overflow-hidden">
                <div className={`${darkMode ? 'bg-gray-700' : 'bg-gray-50'
                  } p-2 flex justify-between items-center`}>
                  <div className={`truncate text-sm ${darkMode ? 'text-gray-300' : 'text-gray-600'}`}>
                    {currentUrl}
                  </div>
                  <a
                    href={currentUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className={`${darkMode ? 'text-blue-400 hover:text-blue-300' : 'text-blue-600 hover:text-blue-800'
                      } flex items-center gap-1`}
                  >
                    <ExternalLink className="w-4 h-4" />
                  </a>
                </div>
                <iframe
                  src={currentUrl}
                  className="w-full h-full border-0"
                  title="Source Preview"
                />
              </div>
            )}
          </div>
        ) : (
          <div className={`p-4 ${darkMode ? 'text-gray-400' : 'text-gray-600'} text-center`}>
            {transcriptions.length === 0 ? "No sources yet. Start recording to see sources." : "No sources found for this transcription."}
          </div>
        )}
      </div>
    );
  };

  return (
    <div className={`min-h-screen ${darkMode ? 'bg-gray-900' : 'bg-gray-100'}`}>
      <Toaster
        position="bottom-right"
        toastOptions={{
          duration: 4000,
          style: {
            background: darkMode ? '#374151' : '#ffffff',
            color: darkMode ? '#ffffff' : '#1f2937',
          },
        }}
      />

      <div className="container mx-auto px-4 py-8">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6">
          <div>
            <h1 className={`text-2xl sm:text-3xl font-bold font-display ${darkMode ? 'text-white' : 'text-gray-900'}`}>
              Jamie, Look That Up
            </h1>
            <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-500'}`}>
              Take on the forces with your JRE Jamie
            </p>
          </div>

          <div className="flex items-center gap-4">
            <button
              onClick={() => setDarkMode(!darkMode)}
              className={`p-2 rounded-lg ${darkMode
                ? 'bg-gray-800 text-yellow-400 hover:bg-gray-700'
                : 'bg-gray-200 text-gray-800 hover:bg-gray-300'
                }`}
              aria-label="Toggle dark mode"
            >
              {darkMode ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
            </button>

            <RecordingControls />
          </div>
        </div>

        <div className={`mb-8 ${darkMode ? 'bg-gray-800' : 'bg-white'} rounded-lg shadow-lg overflow-hidden`}>
          <div className="p-4 border-b border-gray-700">
            <h2 className={`text-xl font-semibold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
              Transcription Timeline
            </h2>
          </div>

          <div className={`px-4 py-3 ${darkMode ? 'bg-gray-700/50' : 'bg-gray-50'} border-b border-gray-700`}>
            <div className="flex items-center gap-2 mb-1">
              <MessageSquareText className={`w-4 h-4 ${darkMode ? 'text-gray-400' : 'text-gray-500'}`} />
              <span className={`text-xs font-medium ${darkMode ? 'text-gray-400' : 'text-gray-500'}`}>
                Conversation Summary
              </span>
              {isSummarizing && (
                <Loader2 className={`w-3 h-3 animate-spin ${darkMode ? 'text-gray-400' : 'text-gray-500'}`} />
              )}
            </div>
            {conversationSummary && (
              <p className={`text-sm ${darkMode ? 'text-gray-300' : 'text-gray-600'}`}>
                {conversationSummary}
              </p>
            )}
          </div>

          <div className="p-4">
            <TranscriptionTimeline
              transcriptions={transcriptions}
              selectedId={selectedTranscriptionId}
              darkMode={darkMode}
              onSelect={handleTranscriptionSelect}
            />

            {liveTranscription && (
              <div className={`mt-4 p-4 rounded-lg ${darkMode ? 'bg-gray-700' : 'bg-gray-50'
                } ${isRecording ? 'border-2 border-red-500 animate-pulse' : ''}`}>
                <p className={`text-lg ${darkMode ? 'text-gray-200' : 'text-gray-800'}`}>
                  {liveTranscription}
                </p>
              </div>
            )}
          </div>
        </div>

        <div className="block md:hidden">
          <MobileLayout
            darkMode={darkMode}
            keywordPanel={<KeywordPanel />}
            analysisPanel={<AnalysisPanel />}
            sourcesPanel={<SourcesPanel />}
          />
        </div>

        <div className="hidden md:grid grid-cols-12 gap-6">
          <div className="col-span-3">
            <div className={`${darkMode ? 'bg-gray-800' : 'bg-white'
              } rounded-lg shadow-lg overflow-hidden`}>
              <div className="p-4 border-b border-gray-700">
                <h2 className={`text-xl font-semibold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                  Keyword Bank
                </h2>
              </div>
              <KeywordPanel />
            </div>
          </div>

          <div className="col-span-9 space-y-6">
            <div className={`${darkMode ? 'bg-gray-800' : 'bg-white'
              } rounded-lg shadow-lg overflow-hidden`}>
              <div className="p-4 border-b border-gray-700">
                <h2 className={`text-xl font-semibold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                  Analysis
                </h2>
              </div>
              <AnalysisPanel />
            </div>

            <div className={`${darkMode ? 'bg-gray-800' : 'bg-white'
              } rounded-lg shadow-lg overflow-hidden`}>
              <div className="p-4 border-b border-gray-700">
                <h2 className={`text-xl font-semibold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                  Sources
                </h2>
              </div>
              <SourcesPanel />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;