import { useState, useEffect, useCallback, useMemo } from 'react';
import { Moon, Sun, Mic, MicOff, Loader2, X, ExternalLink, MessageSquareText, ChevronDown, ChevronUp, Lightbulb, Info } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Toaster, toast } from 'react-hot-toast';
import { updateSession } from './lib/firebase';
import { analyzeWithGemini } from './lib/gemini';
import { formatAnalysisWithLinks, extractKeywords } from './lib/formatters';
import { searchSources, SearchResult } from './lib/searchSources';
import { useSpeechRecognition } from './hooks/useSpeechRecognition';
import { TranscriptionTimeline } from './components/TranscriptionTimeline';
import { MobileLayout } from './components/MobileLayout';

interface Transcription {
  id: string;
  text: string;
  timestamp: string;
  isAnalyzed: boolean;
  keywords?: string[];
  selectedKeywords?: string[];
  analysis?: string;
  sources?: SearchResult[];
  summary?: string;
}

function App() {
  const [darkMode, setDarkMode] = useState(() => {
    const savedMode = localStorage.getItem('darkMode');
    return savedMode ? JSON.parse(savedMode) : false;
  });

  const [transcriptions, setTranscriptions] = useState<Transcription[]>([]);
  const [liveTranscription, setLiveTranscription] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [error, setError] = useState('');
  const [allKeywords, setAllKeywords] = useState<string[]>([]);
  const [conversationSummary, setConversationSummary] = useState('');
  const [selectedTranscriptionId, setSelectedTranscriptionId] = useState<string | null>(null);
  const [isInSession, _setIsInSession] = useState(false);
  const [sessionCode, _setSessionCode] = useState('');
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [_currentTranscriptionText, setCurrentTranscriptionText] = useState<string | null>(null);
  const [isSummaryCollapsed, setIsSummaryCollapsed] = useState(true);
  const [diveDeeper, setDiveDeeper] = useState('');
  const [hasUnreadSummary, setHasUnreadSummary] = useState(false);

  useEffect(() => {
    if (transcriptions.length > 0) {
      const latestTranscription = transcriptions[0];
      setSelectedTranscriptionId(latestTranscription.id);
      setCurrentTranscriptionText(latestTranscription.text);
    }
  }, [transcriptions]);

  const speechRecognitionConfig = useMemo(() => ({
    onBatchComplete: async (text: string) => {
      const transcription: Transcription = {
        id: Date.now().toString(),
        text,
        timestamp: new Date().toISOString(),
        isAnalyzed: false,
        keywords: [],
        selectedKeywords: [],
        analysis: '',
        sources: [],
        summary: ''
      };
      setTranscriptions(prev => [transcription, ...prev]);
      await processTranscription(transcription);
    },
    onLiveTranscription: setLiveTranscription,
    onError: (error: string) => {
      toast.error(error);
    }
  }), []);

  const { isRecording, startRecording, stopRecording } = useSpeechRecognition(speechRecognitionConfig);

  useEffect(() => {
    localStorage.setItem('darkMode', JSON.stringify(darkMode));
    if (darkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [darkMode]);

  const processTranscription = useCallback(async (transcriptionToProcess: Transcription) => {
    try {
      setIsProcessing(true);
      setError('');
      setCurrentTranscriptionText(transcriptionToProcess.text);

      const { analysis: keywordsResponse } = await analyzeWithGemini(transcriptionToProcess.text, [], true);
      if (!keywordsResponse) {
        throw new Error('Failed to extract keywords');
      }
      const newKeywords = extractKeywords(keywordsResponse);
      if (!newKeywords || !Array.isArray(newKeywords)) {
        throw new Error('Invalid keywords format received');
      }

      setIsSummarizing(true);
      const keywordsForAnalysis = transcriptionToProcess.selectedKeywords || [];
      const { analysis, summary, diveDeeper: newDiveDeeper, searchQuery } = await analyzeWithGemini(
        transcriptionToProcess.text,
        keywordsForAnalysis,
        false,
        transcriptions.map(t => ({ text: t.text, timestamp: t.timestamp }))
      );

      if (!analysis) {
        throw new Error('Failed to generate analysis');
      }
      if (!summary) {
        console.warn("Conversation summary was not generated by Gemini API.");
      }

      // DETERMINISTIC SEARCH LOGIC
      // Case A: Active Mode (User selected keywords)
      // Use the specific keywords user selected
      // Case B: Passive Mode (No selection)
      // Use the AI-generated high-quality search query, fallback to extracted keywords

      let searchTerms: string[] = [];

      if (keywordsForAnalysis.length > 0) {
        // Active Mode: Strictly search for selected keywords
        searchTerms = keywordsForAnalysis;
      } else if (searchQuery) {
        // Passive Mode: Use AI-curated query
        searchTerms = [searchQuery]; // searchSources handles array
      } else {
        // Fallback Passive
        searchTerms = newKeywords;
      }

      // Search for real sources using Google Custom Search
      const newSources = await searchSources(searchTerms);

      setAllKeywords(prev => {
        const uniqueKeywords = [...new Set([...prev, ...newKeywords])];
        return uniqueKeywords.sort();
      });

      setTranscriptions(prev =>
        prev.map(t =>
          t.id === transcriptionToProcess.id ? {
            ...t,
            isAnalyzed: true,
            keywords: newKeywords,
            analysis: analysis,
            sources: newSources,
            summary: summary
          } : t
        )
      );

      if (summary) {
        setConversationSummary(summary);
        setHasUnreadSummary(true);
      }
      if (newDiveDeeper) {
        setDiveDeeper(newDiveDeeper);
        setHasUnreadSummary(true);
      }

      if (isInSession && sessionCode) {
        await updateSession(sessionCode, {
          transcriptions,
          analysis,
          urlList: newSources.map((s: SearchResult) => s.link),
          keywords: allKeywords,
          summary
        });
      }

    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'An unknown error occurred';
      console.error('Error processing transcription:', errorMessage);
      toast.error(`Failed to process transcription: ${errorMessage}`);
      setError(errorMessage);
    } finally {
      setIsProcessing(false);
      setIsSummarizing(false);
      setCurrentTranscriptionText(null);
    }
  }, [transcriptions, isInSession, sessionCode, allKeywords]);

  const clearConversation = useCallback(() => {
    setTranscriptions([]);
    setAllKeywords([]);
    setConversationSummary('');
    setCurrentTranscriptionText(null);
    setSelectedTranscriptionId(null);
    setHasUnreadSummary(false);
    setDiveDeeper('');
    toast.success('Conversation cleared');
  }, []);

  const toggleKeyword = useCallback((keyword: string, transcriptionId: string) => {
    setTranscriptions(prev =>
      prev.map(t => {
        if (t.id === transcriptionId) {
          const isSelected = t.selectedKeywords?.includes(keyword);
          const updatedKeywords = isSelected
            ? t.selectedKeywords?.filter(k => k !== keyword) || []
            : [...(t.selectedKeywords || []), keyword];

          if (t.isAnalyzed) {
            processTranscription({ ...t, selectedKeywords: updatedKeywords });
          }

          return { ...t, selectedKeywords: updatedKeywords };
        }
        return t;
      })
    );
  }, [processTranscription]);

  const handleTranscriptionSelect = useCallback((id: string) => {
    setSelectedTranscriptionId(id);
    const transcription = transcriptions.find(t => t.id === id);
    if (transcription) {
      setCurrentTranscriptionText(transcription.text);
    }
  }, [transcriptions]);

  const renderAnalysis = (analysisText: string | undefined) => {
    return (
      <div
        dangerouslySetInnerHTML={{
          __html: formatAnalysisWithLinks(analysisText || '')
        }}
      />
    );
  };

  const RecordingControls = () => (
    <div className="flex gap-3">
      <button
        onClick={startRecording}
        disabled={isRecording}
        className={`p-3 rounded-full transition-all ${isRecording
          ? 'bg-surface-200 cursor-not-allowed opacity-50'
          : 'bg-primary-500 hover:bg-primary-600 shadow-md hover:shadow-lg hover:scale-105'
          }`}
        aria-label="Start Recording"
      >
        <Mic className={`w-5 h-5 ${isRecording ? 'text-surface-500' : 'text-white'}`} />
      </button>

      <button
        onClick={stopRecording}
        disabled={!isRecording}
        className={`p-3 rounded-full transition-all ${!isRecording
          ? 'bg-surface-200 cursor-not-allowed opacity-50'
          : 'bg-coral hover:bg-red-500 shadow-md hover:shadow-lg'
          }`}
        aria-label="Stop Recording"
      >
        <MicOff className="w-5 h-5 text-white" />
      </button>

      <button
        onClick={clearConversation}
        className={`p-3 rounded-full transition-all ${darkMode
          ? 'bg-surface-800 text-surface-200 hover:bg-surface-700'
          : 'bg-surface-100 text-surface-600 hover:bg-surface-200'
          }`}
        aria-label="Clear Conversation"
      >
        <X className="w-5 h-5" />
      </button>
    </div>
  );

  const KeywordPanel = () => {
    const uniqueKeywordsFromAll = useMemo(() => {
      const keywords = transcriptions.reduce((acc: string[], t) => {
        return [...acc, ...(t.keywords || [])];
      }, []);
      return [...new Set(keywords)].sort();
    }, [transcriptions]);

    const lastTranscription = transcriptions[0];
    const selectedKeywordsForLast = lastTranscription?.selectedKeywords || [];

    return (
      <div className="p-6 h-full overflow-y-auto custom-scrollbar">
        <ul className="flex flex-col gap-3">
          {uniqueKeywordsFromAll.map((keyword, index) => (
            <li key={index}>
              <button
                onClick={() => lastTranscription && toggleKeyword(keyword, lastTranscription.id)}
                disabled={!lastTranscription}
                className={`text-left text-sm transition-all ${selectedKeywordsForLast.includes(keyword)
                  ? 'text-primary-600 font-semibold pl-2 border-l-2 border-primary-500'
                  : 'keyword-link'
                  } ${!lastTranscription ? 'opacity-50 cursor-not-allowed no-underline' : ''}`}
              >
                {keyword}
              </button>
            </li>
          ))}
          {uniqueKeywordsFromAll.length === 0 && (
            <li className={`text-sm italic ${darkMode ? 'text-surface-500' : 'text-surface-400'}`}>
              No keywords yet...
            </li>
          )}
        </ul>
      </div>
    );
  };

  const AnalysisPanel = () => {
    const selectedTranscription = transcriptions.find(t => t.id === selectedTranscriptionId);
    const analysisToRender = selectedTranscription?.analysis;

    return (
      <div className="p-8 h-full overflow-y-auto custom-scrollbar">
        {isProcessing ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 className={`w-8 h-8 animate-spin ${darkMode ? 'text-primary-400' : 'text-primary-500'}`} />
          </div>
        ) : error ? (
          <div className={`${darkMode ? 'bg-red-900/20 border-red-900' : 'bg-red-50 border-red-100'} border p-4 rounded-lg`}>
            <p className={`${darkMode ? 'text-red-300' : 'text-red-600'}`}>Error: {error}</p>
          </div>
        ) : analysisToRender ? (
          <div className={`prose ${darkMode ? 'prose-invert' : ''} max-w-none`}>
            {renderAnalysis(analysisToRender)}
          </div>
        ) : (
          <div className={`p-4 ${darkMode ? 'text-surface-500' : 'text-surface-400'} text-center italic mt-12`}>
            {transcriptions.length === 0 ? "Start recording to see analysis." : "Select a transcription to view its analysis."}
          </div>
        )}
      </div>
    );
  };

  const SourcesPanel = () => {
    const selectedTranscription = transcriptions.find(t => t.id === selectedTranscriptionId);
    const sourcesToRender = selectedTranscription?.sources || [];

    return (
      <div className="p-6 h-full overflow-y-auto custom-scrollbar">
        {isProcessing ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 className={`w-8 h-8 animate-spin ${darkMode ? 'text-primary-400' : 'text-primary-500'}`} />
          </div>
        ) : sourcesToRender.length > 0 ? (
          <div className="space-y-4">
            {sourcesToRender.map((source, index) => (
              <a
                key={index}
                href={source.link}
                target="_blank"
                rel="noopener noreferrer"
                className={`block p-4 rounded-lg border transition-colors ${darkMode
                  ? 'bg-surface-800 border-surface-700 hover:border-surface-600'
                  : 'bg-white border-surface-200 hover:border-surface-300'
                  }`}
              >
                <div className="flex items-start gap-3">
                  <ExternalLink className={`w-4 h-4 mt-1 flex-shrink-0 ${darkMode ? 'text-primary-400' : 'text-primary-500'
                    }`} />
                  <div className="flex-1 min-w-0">
                    <h3 className={`font-medium text-sm mb-1 line-clamp-2 ${darkMode ? 'text-surface-100' : 'text-surface-800'
                      }`}>
                      {source.title}
                    </h3>
                    <p className={`text-xs mb-2 line-clamp-2 ${darkMode ? 'text-surface-400' : 'text-surface-500'
                      }`}>
                      {source.snippet}
                    </p>
                    <span className={`text-xs ${darkMode ? 'text-primary-400' : 'text-primary-600'
                      }`}>
                      {source.displayLink}
                    </span>
                  </div>
                </div>
              </a>
            ))}
          </div>
        ) : (
          <div className={`p-4 ${darkMode ? 'text-surface-500' : 'text-surface-400'} text-center italic mt-12`}>
            {selectedTranscriptionId
              ? "No sources found for this topic."
              : "Select a transcription to see relevant sources."}
          </div>
        )}
      </div>
    );
  };

  return (
    <div className={`min-h-screen ${darkMode ? 'bg-surface-950 text-surface-0' : 'bg-surface-0 text-surface-900'} transition-colors duration-300`}>
      <Toaster
        position="bottom-right"
        toastOptions={{
          duration: 4000,
          style: {
            background: darkMode ? '#262626' : '#ffffff', // surface-800 / surface-0
            color: darkMode ? '#ffffff' : '#171717', // surface-0 / surface-900
            border: darkMode ? '1px solid #404040' : '1px solid #e5e5e5',
          },
        }}
      />

      <div className="container mx-auto px-4 md:px-8 py-8 md:py-12">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8 md:mb-12">
          <div>
            <h1 className="text-4xl md:text-5xl font-bold font-display tracking-tight mb-2">
              Jamie, Look That Up
            </h1>
            <p className={`text-lg font-light ${darkMode ? 'text-surface-400' : 'text-surface-500'}`}>
              Take on the forces with JRE Jamie
            </p>
          </div>

          <div className="flex items-center gap-4">
            <Link
              to="/about"
              className={`p-3 rounded-full transition-colors ${darkMode
                ? 'bg-surface-800 text-surface-400 hover:bg-surface-700 hover:text-surface-200'
                : 'bg-surface-100 text-surface-500 hover:bg-surface-200 hover:text-surface-700'
                }`}
              aria-label="About"
            >
              <Info className="w-5 h-5" />
            </Link>
            <button
              onClick={() => setDarkMode(!darkMode)}
              className={`p-3 rounded-full transition-colors ${darkMode
                ? 'bg-surface-800 text-yellow-400 hover:bg-surface-700'
                : 'bg-surface-100 text-surface-600 hover:bg-surface-200'
                }`}
              aria-label="Toggle dark mode"
            >
              {darkMode ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
            </button>

            <RecordingControls />
          </div>
        </div>

        <div className={`mb-12 ${darkMode ? 'card-dark' : 'card'} overflow-hidden`}>
          <div className={`p-6 border-b ${darkMode ? 'border-surface-800' : 'border-surface-200'}`}>
            <h2 className="section-title text-2xl">
              Transcription Timeline
            </h2>
          </div>

          <div className={`px-6 py-4 ${darkMode ? 'bg-surface-900/50' : 'bg-surface-50'} border-b ${darkMode ? 'border-surface-800' : 'border-surface-200'}`}>
            <button
              onClick={() => {
                const willExpand = isSummaryCollapsed;
                setIsSummaryCollapsed(!isSummaryCollapsed);
                if (willExpand) {
                  // User is expanding the summary, mark as read
                  setHasUnreadSummary(false);
                }
              }}
              className="flex items-center justify-between w-full group"
            >
              <div className="flex items-center gap-3">
                <MessageSquareText className={`w-4 h-4 ${darkMode ? 'text-surface-400' : 'text-surface-500'}`} />
                <span className={`text-xs font-medium uppercase tracking-wider ${darkMode ? 'text-surface-400' : 'text-surface-500'}`}>
                  Summary
                </span>
                {isSummarizing ? (
                  <Loader2 className={`w-3 h-3 animate-spin ${darkMode ? 'text-primary-400' : 'text-primary-500'}`} />
                ) : hasUnreadSummary && (conversationSummary || diveDeeper) ? (
                  <span className="w-2 h-2 rounded-full bg-blue-500" />
                ) : null}
              </div>
              {isSummaryCollapsed ? (
                <ChevronDown className={`w-4 h-4 ${darkMode ? 'text-surface-500' : 'text-surface-400'} group-hover:text-primary-500 transition-colors`} />
              ) : (
                <ChevronUp className={`w-4 h-4 ${darkMode ? 'text-surface-500' : 'text-surface-400'} group-hover:text-primary-500 transition-colors`} />
              )}
            </button>

            {!isSummaryCollapsed && (
              <div className="mt-4 space-y-4 animate-in fade-in slide-in-from-top-2 duration-300">
                {conversationSummary && (
                  <p className={`text-base leading-relaxed ${darkMode ? 'text-surface-300' : 'text-surface-600'}`}>
                    {conversationSummary}
                  </p>
                )}
                {diveDeeper && (
                  <div className={`flex items-start gap-3 pt-3 border-t ${darkMode ? 'border-surface-700' : 'border-surface-200'}`}>
                    <Lightbulb className={`w-4 h-4 mt-0.5 flex-shrink-0 ${darkMode ? 'text-amber-400' : 'text-amber-500'}`} />
                    <div>
                      <span className={`text-xs font-medium uppercase tracking-wider ${darkMode ? 'text-surface-500' : 'text-surface-400'}`}>
                        Dive Deeper
                      </span>
                      <p className={`mt-1 text-base italic leading-relaxed ${darkMode ? 'text-surface-300' : 'text-surface-600'}`}>
                        {diveDeeper}
                      </p>
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>

          <div className="p-6">
            <TranscriptionTimeline
              transcriptions={transcriptions}
              selectedId={selectedTranscriptionId}
              darkMode={darkMode}
              onSelect={handleTranscriptionSelect}
            />

            {liveTranscription && (
              <div className={`mt-6 p-6 rounded-lg border ${darkMode ? 'bg-surface-900 border-primary-500/20' : 'bg-surface-50 border-primary-500/20'
                } ${isRecording ? 'animate-pulse' : ''}`}>
                <p className={`text-xl font-light leading-relaxed ${darkMode ? 'text-surface-200' : 'text-surface-800'}`}>
                  {liveTranscription}
                </p>
              </div>
            )}
          </div>
        </div>

        <div className="block md:hidden">
          <MobileLayout
            darkMode={darkMode}
            keywordPanel={<KeywordPanel />}
            analysisPanel={<AnalysisPanel />}
            sourcesPanel={<SourcesPanel />}
          />
        </div>

        <div className="hidden md:grid grid-cols-12 gap-8">
          <div className="col-span-3">
            <div className={`h-full ${darkMode ? 'card-dark' : 'card'} overflow-hidden flex flex-col`}>
              <div className={`p-6 border-b ${darkMode ? 'border-surface-800' : 'border-surface-200'}`}>
                <h2 className="section-title">
                  Keywords
                </h2>
              </div>
              <KeywordPanel />
            </div>
          </div>

          <div className="col-span-9 grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className={`h-[600px] ${darkMode ? 'card-dark' : 'card'} overflow-hidden flex flex-col`}>
              <div className={`p-6 border-b ${darkMode ? 'border-surface-800' : 'border-surface-200'}`}>
                <h2 className="section-title">
                  Analysis
                </h2>
              </div>
              <AnalysisPanel />
            </div>

            <div className={`h-[600px] ${darkMode ? 'card-dark' : 'card'} overflow-hidden flex flex-col`}>
              <div className={`p-6 border-b ${darkMode ? 'border-surface-800' : 'border-surface-200'}`}>
                <h2 className="section-title">
                  Sources
                </h2>
              </div>
              <SourcesPanel />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;